/**
 * Stub for the Emscripten-generated Konclude WASM module.
 *
 * This file allows `ts/worker.ts` to import `./konclude.mjs` during
 * development and testing without the actual WASM build artefact.
 *
 * In unit tests, this module is replaced by `vi.mock()`.
 * At runtime, this file is NOT shipped — the real `dist/konclude.mjs`
 * generated by Emscripten takes its place.
 */

export default function createKoncludeModule() {
  throw new Error(
    "konclude.mjs stub: the real WASM module has not been built yet. " +
      "Run `npm run build:wasm` (requires Docker + Emscripten) to produce " +
      "the actual dist/konclude.mjs + dist/konclude.wasm artefacts.",
  );
}
