#!/usr/bin/env bash
# Patch Emscripten-generated dist/konclude.mjs after each WASM build.
#
# Two issues fixed here (neither can be fixed upstream without patching Emscripten):
#
#   1. createRequire import — first two lines use Node.js `createRequire` which
#      throws ReferenceError in browsers. The require() it creates is only used
#      in the ENVIRONMENT_IS_NODE branch, which is never reached in a browser.
#
#   2. pthread worker.onerror re-throw — when a pthread pool thread exits cleanly
#      it throws its exit-status code (e.g. 21102936). Chrome wraps this as
#      ErrorEvent { message: "uncaught exception: 21102936" }. The generated
#      onerror handler throws unconditionally, crashing the outer Worker and
#      rejecting pending calls. Fix: suppress the throw for numeric exit codes.
#
# The script is idempotent — it checks whether each patch is already applied
# before modifying the file.

set -euo pipefail

DIST_FILE="dist/konclude.mjs"

if [[ ! -f "$DIST_FILE" ]]; then
  echo "patch-konclude-mjs: $DIST_FILE not found — run 'make build-wasm' first" >&2
  exit 1
fi

# ── Patch 1: replace createRequire static import with conditional await ──────
# The static `import { createRequire } from 'module'` crashes browsers because
# 'module' is a Node.js built-in not available as a browser URL.
# Replace with a top-level await that only runs in Node.js (browsers skip it).
# Top-level await is safe: Node.js ≥14.8, Chrome ≥89, Firefox ≥89, Safari ≥15.
if grep -qF "import { createRequire } from 'module';" "$DIST_FILE"; then
  python3 - "$DIST_FILE" <<'PYEOF'
import sys
path = sys.argv[1]
text = open(path).read()
old = "import { createRequire } from 'module';\nconst require = createRequire(import.meta.url);\n"
new = "const require = (typeof process === 'object' && process.versions && process.versions.node) ? (await import('module')).createRequire(import.meta.url) : undefined;\n"
if old not in text:
    # Try without trailing newline variations
    import re
    text2 = re.sub(
        r"import \{ createRequire \} from 'module';\s*const require = createRequire\(import\.meta\.url\);\s*",
        new,
        text,
        count=1
    )
    if text2 == text:
        print("patch-konclude-mjs: [WARN]  createRequire pattern not matched exactly — manual check needed")
        sys.exit(0)
    open(path, 'w').write(text2)
else:
    open(path, 'w').write(text.replace(old, new, 1))
PYEOF
  echo "patch-konclude-mjs: [APPLIED] replaced createRequire with conditional await"
else
  echo "patch-konclude-mjs: [SKIP]    createRequire already replaced"
fi

# ── Patch 2: suppress numeric pthread exit codes in worker.onerror ───────────
# Before: throw e
# After:  if(!/\b\d{5,}\b/.test(String(e.message||"")))throw e
#
# We match the exact pattern generated by Emscripten to avoid false positives.
BEFORE='err(`${message} ${e.filename}:${e.lineno}: ${e.message}`);throw e'
AFTER='err(`${message} ${e.filename}:${e.lineno}: ${e.message}`);if(!/\\b\\d{5,}\\b/.test(String(e.message||"")))throw e'

if grep -qF "$BEFORE" "$DIST_FILE"; then
  # Use python3 for reliable literal-string substitution (avoids sed escaping hell)
  python3 - "$DIST_FILE" <<'PYEOF'
import sys
path = sys.argv[1]
before = 'err(`${message} ${e.filename}:${e.lineno}: ${e.message}`);throw e'
after  = 'err(`${message} ${e.filename}:${e.lineno}: ${e.message}`);if(!/\\b\\d{5,}\\b/.test(String(e.message||"")))throw e'
text = open(path).read()
if before not in text:
    print("patch-konclude-mjs: [SKIP]    onerror patch — pattern not found (already patched?)")
    sys.exit(0)
open(path, 'w').write(text.replace(before, after, 1))
PYEOF
  echo "patch-konclude-mjs: [APPLIED] patched worker.onerror to suppress numeric exits"
else
  echo "patch-konclude-mjs: [SKIP]    worker.onerror already patched"
fi

# ── Patch 3: no-op __emscripten_thread_free_data ─────────────────────────────
# After classify(), KPSet processor pthreads exit and post cmd=cleanupThread.
# returnWorkerToPool() calls __emscripten_thread_free_data(pthread_ptr), which
# is a WASM export that calls back into C++ state that may already be in an
# undefined state (stale vtable pointer → getWasmTableEntry(0x72676E73) crash).
# No-op the function: the thread descriptor memory leaks (one per pthread pool
# thread, fixed count) but the crash is eliminated.
BEFORE_FREE='var __emscripten_thread_free_data=a0=>(__emscripten_thread_free_data=wasmExports["vc"])(a0);'
AFTER_FREE='var __emscripten_thread_free_data=a0=>{};'

if grep -qF "$BEFORE_FREE" "$DIST_FILE"; then
  python3 - "$DIST_FILE" <<'PYEOF'
import sys
path = sys.argv[1]
before = 'var __emscripten_thread_free_data=a0=>(__emscripten_thread_free_data=wasmExports["vc"])(a0);'
after  = 'var __emscripten_thread_free_data=a0=>{};'
text = open(path).read()
open(path, 'w').write(text.replace(before, after, 1))
PYEOF
  echo "patch-konclude-mjs: [APPLIED] no-op __emscripten_thread_free_data"
else
  echo "patch-konclude-mjs: [SKIP]    __emscripten_thread_free_data already patched"
fi

# ── Patch 4: guard invokeEntryPoint against vtable corruption crashes ─────────
# KPSet processor pthreads crash with getWasmTableEntry(0x72676E73) ("sngr" —
# freed memory reused for string data) inside their thread function after
# classify() has already returned.  The work is done; the crash is in cleanup
# code that runs on shared memory already freed by the previous call cycle.
# Wrapping the thread entry in a try-catch prevents the error event from
# reaching the main Worker's onerror handler (which would reject pending RPC
# promises with "unwind").
BEFORE_ENTRY='var invokeEntryPoint=(ptr,arg)=>{runtimeKeepaliveCounter=0;noExitRuntime=0;var result=getWasmTableEntry(ptr)(arg);function finish(result){if(keepRuntimeAlive()){EXITSTATUS=result}else{__emscripten_thread_exit(result)}}finish(result)};'
# On crash: log, call __emscripten_thread_exit(0) so pthread_join (which uses
# Atomics.wait on the thread's exit-status word) can unblock, then return.
# Without the __emscripten_thread_exit call, stopThread(true)/pthread_join hangs.
AFTER_ENTRY='var invokeEntryPoint=(ptr,arg)=>{runtimeKeepaliveCounter=0;noExitRuntime=0;var result;try{result=getWasmTableEntry(ptr)(arg);}catch(e){err("invokeEntryPoint: thread ptr="+ptr+" crashed: "+(e&&e.message));__emscripten_thread_exit(0);return;}function finish(result){if(keepRuntimeAlive()){EXITSTATUS=result}else{__emscripten_thread_exit(result)}}finish(result)};'

if grep -qF "$BEFORE_ENTRY" "$DIST_FILE"; then
  python3 - "$DIST_FILE" <<'PYEOF'
import sys
path = sys.argv[1]
before = 'var invokeEntryPoint=(ptr,arg)=>{runtimeKeepaliveCounter=0;noExitRuntime=0;var result=getWasmTableEntry(ptr)(arg);function finish(result){if(keepRuntimeAlive()){EXITSTATUS=result}else{__emscripten_thread_exit(result)}}finish(result)};'
after  = 'var invokeEntryPoint=(ptr,arg)=>{runtimeKeepaliveCounter=0;noExitRuntime=0;var result;try{result=getWasmTableEntry(ptr)(arg);}catch(e){err("invokeEntryPoint: thread ptr="+ptr+" crashed: "+(e&&e.message));__emscripten_thread_exit(0);return;}function finish(result){if(keepRuntimeAlive()){EXITSTATUS=result}else{__emscripten_thread_exit(result)}}finish(result)};'
text = open(path).read()
open(path, 'w').write(text.replace(before, after, 1))
PYEOF
  echo "patch-konclude-mjs: [APPLIED] guarded invokeEntryPoint against vtable crashes"
else
  echo "patch-konclude-mjs: [SKIP]    invokeEntryPoint already guarded"
fi

# ── Patch 5: add @vite-ignore to pthread Worker creation ─────────────────────
# Vite's vite:worker-import-meta-url plugin crashes with an unhandled exception
# when it encounters the dynamic workerOptions variable in the pthread Worker
# creation call.  Adding /* @vite-ignore */ tells the plugin to skip this call,
# preventing the crash so the module can be served in Vite dev-server contexts
# (used by the browser integration tests).
BEFORE_VITE_WORKER='worker=new Worker(new URL("konclude.mjs",import.meta.url),workerOptions)'
AFTER_VITE_WORKER='worker=new Worker(new URL("konclude.mjs",_scriptName),/* @vite-ignore */workerOptions)'

if grep -qF "$BEFORE_VITE_WORKER" "$DIST_FILE"; then
  python3 - "$DIST_FILE" <<'PYEOF'
import sys
path = sys.argv[1]
# Change Worker URL base from import.meta.url to _scriptName (same value, set
# earlier as var _scriptName = import.meta.url).  This breaks the regex pattern
# that Vite's vite:worker-import-meta-url plugin uses to detect Worker bundles
# (which requires "new URL(..., import.meta.url)"), preventing Vite from
# rewriting the URL and appending ?worker query parameters that break runtime.
# Also add /* @vite-ignore */ in the options as a secondary safety measure.
before = 'worker=new Worker(new URL("konclude.mjs",import.meta.url),workerOptions)'
after  = 'worker=new Worker(new URL("konclude.mjs",_scriptName),/* @vite-ignore */workerOptions)'
text = open(path).read()
open(path, 'w').write(text.replace(before, after, 1))
PYEOF
  echo "patch-konclude-mjs: [APPLIED] use _scriptName in pthread Worker URL (prevents Vite rewriting)"
else
  echo "patch-konclude-mjs: [SKIP]    pthread Worker already uses _scriptName"
fi

# ── Patch 6: allow on-demand worker allocation in browser ────────────────────
# Emscripten's getNewWorker() bails with `return` (returns undefined) when the
# pthread pool is exhausted AND ENVIRONMENT_IS_NODE is false (i.e. in browsers).
# Konclude's KPSet classifier starts all 8 pool workers, and each worker then
# calls pthread_create to spawn sub-threads.  With a full pool and no on-demand
# allocation, spawnThread() returns EAGAIN.  KPSet spin-waits for a slot that
# never opens (cleanupThread messages are deferred until the main thread unblocks
# from memory.atomic.wait32), causing a permanent deadlock in the browser.
# Fix: remove the !ENVIRONMENT_IS_NODE guard, matching Node.js behaviour.
# Safety: loadWasmModuleToWorker sets worker.onmessage and sends {cmd:"load"}
# before spawnThread sends {cmd:"run"}; workers process them in order.
# {cmd:"loaded"} and {cmd:"cleanupThread"} queue up and are processed when
# the main Emscripten thread returns from WASM after classification completes.
BEFORE_GETNEW='getNewWorker(){if(PThread.unusedWorkers.length==0){if(!ENVIRONMENT_IS_NODE){return}PThread.allocateUnusedWorker();PThread.loadWasmModuleToWorker(PThread.unusedWorkers[0])}return PThread.unusedWorkers.pop()}'
AFTER_GETNEW='getNewWorker(){if(PThread.unusedWorkers.length==0){PThread.allocateUnusedWorker();PThread.loadWasmModuleToWorker(PThread.unusedWorkers[0])}return PThread.unusedWorkers.pop()}'

if grep -qF "$BEFORE_GETNEW" "$DIST_FILE"; then
  python3 - "$DIST_FILE" <<'PYEOF'
import sys
path = sys.argv[1]
before = 'getNewWorker(){if(PThread.unusedWorkers.length==0){if(!ENVIRONMENT_IS_NODE){return}PThread.allocateUnusedWorker();PThread.loadWasmModuleToWorker(PThread.unusedWorkers[0])}return PThread.unusedWorkers.pop()}'
after  = 'getNewWorker(){if(PThread.unusedWorkers.length==0){PThread.allocateUnusedWorker();PThread.loadWasmModuleToWorker(PThread.unusedWorkers[0])}return PThread.unusedWorkers.pop()}'
text = open(path).read()
open(path, 'w').write(text.replace(before, after, 1))
PYEOF
  echo "patch-konclude-mjs: [APPLIED] allow on-demand worker allocation in browser (fix KPSet deadlock)"
else
  echo "patch-konclude-mjs: [SKIP]    getNewWorker already allows on-demand allocation"
fi

# ── Patch 7: increase pthreadPoolSize 8→32 ───────────────────────────────────
# KPSet starts 8 pre-allocated pool workers then spawns ~9 more on-demand during
# classification (total ~17 threads).  Browser Chromium silently defers/drops
# script evaluation for workers created mid-classification while 8+ WASM threads
# are already running — on-demand workers are allocated, their HTTP fetch
# succeeds, but the module never evaluates.  Pre-allocating 20 workers at module
# init time ensures all threads are ready before classify() is called, avoiding
# on-demand creation entirely.  20 gives 3 units of margin beyond observed peak.
BEFORE_POOL='var pthreadPoolSize=8;'
AFTER_POOL='var pthreadPoolSize=32;'

if grep -qF "$BEFORE_POOL" "$DIST_FILE"; then
  python3 - "$DIST_FILE" <<'PYEOF'
import sys
path = sys.argv[1]
before = 'var pthreadPoolSize=8;'
after  = 'var pthreadPoolSize=32;'
text = open(path).read()
open(path, 'w').write(text.replace(before, after, 1))
PYEOF
  echo "patch-konclude-mjs: [APPLIED] pthreadPoolSize 8→32 (pre-allocate enough workers for KPSet)"
else
  echo "patch-konclude-mjs: [SKIP]    pthreadPoolSize already patched"
fi

echo "patch-konclude-mjs: done"
