#!/usr/bin/env bash
# Patch Emscripten-generated dist/konclude.mjs after each WASM build.
#
# Two issues fixed here (neither can be fixed upstream without patching Emscripten):
#
#   1. createRequire import — first two lines use Node.js `createRequire` which
#      throws ReferenceError in browsers. The require() it creates is only used
#      in the ENVIRONMENT_IS_NODE branch, which is never reached in a browser.
#
#   2. pthread worker.onerror re-throw — when a pthread pool thread exits cleanly
#      it throws its exit-status code (e.g. 21102936). Chrome wraps this as
#      ErrorEvent { message: "uncaught exception: 21102936" }. The generated
#      onerror handler throws unconditionally, crashing the outer Worker and
#      rejecting pending calls. Fix: suppress the throw for numeric exit codes.
#
# The script is idempotent — it checks whether each patch is already applied
# before modifying the file.

set -euo pipefail

DIST_FILE="dist/konclude.mjs"

if [[ ! -f "$DIST_FILE" ]]; then
  echo "patch-konclude-mjs: $DIST_FILE not found — run 'make build-wasm' first" >&2
  exit 1
fi

# ── Patch 1: replace createRequire static import with conditional await ──────
# The static `import { createRequire } from 'module'` crashes browsers because
# 'module' is a Node.js built-in not available as a browser URL.
# Replace with a top-level await that only runs in Node.js (browsers skip it).
# Top-level await is safe: Node.js ≥14.8, Chrome ≥89, Firefox ≥89, Safari ≥15.
if grep -qF "import { createRequire } from 'module';" "$DIST_FILE"; then
  python3 - "$DIST_FILE" <<'PYEOF'
import sys
path = sys.argv[1]
text = open(path).read()
old = "import { createRequire } from 'module';\nconst require = createRequire(import.meta.url);\n"
new = "const require = (typeof process === 'object' && process.versions && process.versions.node) ? (await import('module')).createRequire(import.meta.url) : undefined;\n"
if old not in text:
    # Try without trailing newline variations
    import re
    text2 = re.sub(
        r"import \{ createRequire \} from 'module';\s*const require = createRequire\(import\.meta\.url\);\s*",
        new,
        text,
        count=1
    )
    if text2 == text:
        print("patch-konclude-mjs: [WARN]  createRequire pattern not matched exactly — manual check needed")
        sys.exit(0)
    open(path, 'w').write(text2)
else:
    open(path, 'w').write(text.replace(old, new, 1))
PYEOF
  echo "patch-konclude-mjs: [APPLIED] replaced createRequire with conditional await"
else
  echo "patch-konclude-mjs: [SKIP]    createRequire already replaced"
fi

# ── Patch 2: suppress numeric pthread exit codes in worker.onerror ───────────
# Before: throw e
# After:  if(!/\b\d{5,}\b/.test(String(e.message||"")))throw e
#
# We match the exact pattern generated by Emscripten to avoid false positives.
BEFORE='err(`${message} ${e.filename}:${e.lineno}: ${e.message}`);throw e'
AFTER='err(`${message} ${e.filename}:${e.lineno}: ${e.message}`);if(!/\\b\\d{5,}\\b/.test(String(e.message||"")))throw e'

if grep -qF "$BEFORE" "$DIST_FILE"; then
  # Use python3 for reliable literal-string substitution (avoids sed escaping hell)
  python3 - "$DIST_FILE" <<'PYEOF'
import sys
path = sys.argv[1]
before = 'err(`${message} ${e.filename}:${e.lineno}: ${e.message}`);throw e'
after  = 'err(`${message} ${e.filename}:${e.lineno}: ${e.message}`);if(!/\\b\\d{5,}\\b/.test(String(e.message||"")))throw e'
text = open(path).read()
if before not in text:
    print("patch-konclude-mjs: [SKIP]    onerror patch — pattern not found (already patched?)")
    sys.exit(0)
open(path, 'w').write(text.replace(before, after, 1))
PYEOF
  echo "patch-konclude-mjs: [APPLIED] patched worker.onerror to suppress numeric exits"
else
  echo "patch-konclude-mjs: [SKIP]    worker.onerror already patched"
fi

echo "patch-konclude-mjs: done"
